require 'rake'
require 'rake/clean'
require 'rake/testtask'

CLEAN.include('**/*.gem', '**/*.rbc')

namespace :gem do
  desc 'Build the html-table gem'
  task create: [:clean] do
    require 'rubygems/package'
    spec = eval(IO.read('html-table.gemspec'))
    spec.signing_key = File.join(Dir.home, '.ssh', 'gem-private_key.pem')
    Gem::Package.build(spec, true)
  end

  desc 'Install the html-table package as a gem'
  task install: [:create] do
    file = Dir['*.gem'].first
    sh "gem install -l #{file}"
  end
end

namespace 'example' do
  desc 'Run the first simple html-table example'
  task :simple1 do
    sh 'ruby -Ilib examples/simple1.rb'
  end

  desc 'Run the second simple html-table example'
  task :simple2 do
    sh 'ruby -Ilib examples/simple2.rb'
  end

  desc 'Run the third simple html-table example'
  task :simple3 do
    sh 'ruby -Ilib examples/simple3.rb'
  end

  desc 'Run the first intermediate html-table example'
  task :intermediate1 do
    sh 'ruby -Ilib examples/intermediate1.rb'
  end

  desc 'Run the second intermediate html-table example'
  task :intermediate2 do
    sh 'ruby -Ilib examples/intermediate2.rb'
  end

  desc 'Run the advanced html-table example'
  task :advanced do
    sh 'ruby -Ilib examples/advanced.rb'
  end
end

Rake::TestTask.new do |t|
  t.warning = true
  t.verbose = true
end

namespace 'test' do
  Rake::TestTask.new('attribute_handler') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_attribute_handler.rb']
  end

  Rake::TestTask.new('body') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_body.rb']
  end

  Rake::TestTask.new('caption') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_caption.rb']
  end

  Rake::TestTask.new('col') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_col.rb']
  end

  Rake::TestTask.new('colgroup') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_colgroup.rb']
  end

  Rake::TestTask.new('data') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_data.rb']
  end

  Rake::TestTask.new('foot') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_foot.rb']
  end

  Rake::TestTask.new('head') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_head.rb']
  end

  Rake::TestTask.new('header') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_header.rb']
  end

  Rake::TestTask.new('html_handler') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_html_handler.rb']
  end

  Rake::TestTask.new('row') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_row.rb']
  end

  Rake::TestTask.new('table') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_table.rb']
  end

  Rake::TestTask.new('tablesection') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_tablesection.rb']
  end

  Rake::TestTask.new('tag_handler') do |t|
    t.warning = true
    t.verbose = true
    t.test_files = FileList['test/test_tag_handler.rb']
  end
end

task default: :test
